job1:
  script: 
    - su -c 'docker build --force-rm -t redmine-3.2.0 .'
    - su -c 'docker run -d -p 3000:3000 --name redmine redmine-3.2.0'
    - curl http://127.0.0.1:3000/
    - su -c 'docker stop redmine'
    - su -c 'docker rm redmine'
